# Generated by Django 6.0.4 on 2026-05-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(help_text='course id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='course name', max_length=100, verbose_name='Course Name')),
            ],
        ),
    ]
