# Generated by Django 6.0.4 on 2026-05-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traniee',
            fields=[
                ('id', models.IntegerField(help_text='traniee id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='traniee name', max_length=100, verbose_name='Traniee Name')),
                ('email', models.EmailField(help_text='traniee email', max_length=254, verbose_name='Traniee Email')),
            ],
        ),
    ]
