# Generated by Django 6.0.4 on 2026-05-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_traniee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traniee',
        ),
    ]
