# Generated by Django 6.0.4 on 2026-05-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traniee', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Traniee',
        ),
    ]
