# Generated by Django 6.0.4 on 2026-05-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traniee', '0002_delete_traniee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traniee',
            fields=[
                ('id', models.IntegerField(help_text='traniee id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='traniee name', max_length=100, verbose_name='Traniee Name')),
                ('email', models.EmailField(help_text='traniee email', max_length=254, verbose_name='Traniee Email')),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Insert Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
            ],
        ),
    ]
