# Generated by Django 6.0.4 on 2026-05-10 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_delete_traniee'),
        ('traniee', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traniee',
            name='Course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traniee',
            name='Traniee_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
