# Generated by Django 6.0.4 on 2026-05-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traniee', '0004_traniee_course_traniee_traniee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traniee',
            name='Traniee_image',
            field=models.ImageField(blank=True, null=True, upload_to='trainee_cover/'),
        ),
    ]
