# Generated by Django 6.0.4 on 2026-05-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traniee', '0006_alter_traniee_traniee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='traniee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
